name: cem-wich
channels:
  - conda-forge
  - defaults
dependencies:
  - blosc
  - brotli
  - bzip2
  - ca-certificates
  - certifi
  - charls
  - cloudpickle
  - cycler
  - cytoolz
  - dask-core
  - decorator
  - freetype
  - giflib
  - icc_rt
  - imagecodecs
  - imageio
  - intel-openmp
  - joblib
  - jpeg
  - jxrlib
  - kiwisolver
  - lcms2
  - lerc
  - libaec
  - libblas
  - libcblas
  - liblapack
  - libpng
  - libtiff
  - libwebp-base
  - libzopfli
  - lz4-c
  - matplotlib-base
  - mkl
  - networkx
  - numpy
  - olefile
  - openjpeg
  - openssl
  - pillow
  - pip
  - pyparsing
  - python
  - python-dateutil
  - python_abi
  - pywavelets
  - pyyaml
  - scikit-image
  - scikit-learn
  - scipy
  - setuptools
  - six
  - snappy
  - sqlite
  - threadpoolctl
  - tifffile
  - tk
  - toolz
  - tornado
  - vc
  - vs2015_runtime
  - wheel
  - wincertstore
  - xz
  - yaml
  - zfp
  - zlib
  - zstd
  - pip:
    - cachetools
    - chardet
    - click
    - earthengine-api
    - flask
    - future
    - google-api-core
    - google-api-python-client
    - google-auth
    - google-auth-httplib2
    - google-cloud-core
    - google-cloud-storage
    - google-resumable-media
    - googleapis-common-protos
    - httplib2
    - httplib2shim
    - idna
    - itsdangerous
    - jinja2
    - markupsafe
    - protobuf
    - pyasn1
    - pyasn1-modules
    - pytz
    - requests
    - rsa
    - uritemplate
    - urllib3
    - werkzeug

